# Generated by Django 6.0.7 on 2026-07-16 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TapchanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Raqami')),
                ('item_type', models.CharField(choices=[('tapchan', 'Tapchan'), ('table', 'Stol')], default='tapchan', max_length=10)),
                ('status', models.CharField(choices=[('free', "Bo'sh"), ('booked', 'Band')], default='free', max_length=10)),
                ('is_banket_zone', models.BooleanField(default=False, verbose_name='15-Banket')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('kids_under_6', models.PositiveIntegerField(default=0)),
                ('kids_6_12', models.PositiveIntegerField(default=0)),
                ('adults_13_plus', models.PositiveIntegerField(default=0)),
                ('total_booking_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('tapchans', models.ManyToManyField(related_name='bookings', to='tapchanlar.tapchantable')),
            ],
        ),
    ]
