# Generated by Django 6.0.7 on 2026-07-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tapchanlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapchanQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Kod rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tapchan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tapchanlar.tapchantable')),
            ],
            options={
                'verbose_name': 'QR Kod',
                'verbose_name_plural': 'QR Kodlar',
            },
        ),
    ]
